---
apiVersion: v1
kind: pod
metadata:
  name: pod-1
spec: 
  containers:
    - name: cont-1
      image: shaikmustafa/dm
      ports: 
        - containerPort: 80
      envFrom: 
         SecretRef:
           name: thirdsecret 
           
